#3-RT-Blurbcard-Compoent
MarkPerrie/rocktrust-sanity pull request #18
Opened 2022-10-13 11:50 UTC by DJMF2015

Added blurb card component. Main need some changes. eg) had to split the three paragraphs into different props as very long...

![Screenshot 2022-10-13 at 12 48 07](https://user-images.githubusercontent.com/14128581/195588357-b59b0447-512f-4752-8245-d2039f29578e.jpg)

2022-10-13 13:02 UTC, josephshambrook requested changes

2022-10-13 15:12 UTC, josephshambrook commented on pages/index.js
> +    <>
Don't need a fragment here as only one top-level element (`<Layout>`) is being returned

2022-10-13 15:14 UTC, josephshambrook reviewed
I'll merge this with main to get rid of the conflicts

2022-10-13 15:14 UTC, josephshambrook commented on pages/index.js
> +          {" "}
This can be deleted

2022-10-13 15:14 UTC, josephshambrook commented on pages/index.js
> +          <p className="m-0 p-1.5 text-lg pb-6">
This one has a class of `text-lg` but the rest don't. You would probably want to add this class to the others as well, or remove it from this one.

2022-10-13 15:45 UTC, DJMF2015 commented on pages/index.js
> +          <p className="m-0 p-1.5 text-lg pb-6">
Iam sorry joe i never saw this comment and have got into merge conflicts

2022-10-13 15:46 UTC, DJMF2015 commented on pages/index.js
> +    <>
i  have removed this

2022-10-13 15:49 UTC, DJMF2015 commented on pages/index.js
> +          <p className="m-0 p-1.5 text-lg pb-6">
I have removed the text-lg as i don't feel it is needed looking at the current designs.

2022-10-13 15:50 UTC, DJMF2015 commented on pages/index.js
> +          {" "}
Have left alone as wasn't sure why i would want to delete the buttons.

2022-10-13 15:51 UTC, DJMF2015 commented on components/Blurb.js
> +          <h3 class="m-0 p-1.5 text-lg pb-6">{blurbPara3}</h3>
This bit has been done as per comments.

2022-10-14 07:51 UTC, josephshambrook commented on pages/index.js
> +          {" "}
I didn't mean the buttons, I meant the `{" "}` line

2022-10-14 07:51 UTC, josephshambrook approved these changes

2022-10-14 10:37 UTC, merged